name = "marelle-workers"
main = "CloudflareWorkers/src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# D1 資料庫配置（本地開發）
[[d1_databases]]
binding = "DB"
database_name = "marelle-local"
database_id = "local"

# 本地開發配置
[env.development]
vars = { ENVIRONMENT = "development" }

# 生產環境配置
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "marelle-production"
database_id = "your-production-database-id"