name = "marelle-api"
main = "../backend/API/index.ts"
compatibility_date = "2024-10-01"

# Bind api.marelle.com.tw to this Worker via Routes (zone: marelle.com.tw)
routes = [
	{ pattern = "api.marelle.com.tw/*", zone_name = "marelle.com.tw" }
]

[vars]
ECPAY_ENV = "stage"

# Logistics (stage)
ECPAY_LOGISTICS_C2C_MERCHANT_ID = "2000933"
ECPAY_LOGISTICS_C2C_HASH_KEY = "XBERn1YOvpM9nfZc"
ECPAY_LOGISTICS_C2C_HASH_IV = "h1ONHk4P4yqbl5LK"
ECPAY_LOGISTICS_HOME_MERCHANT_ID = "2000132"
ECPAY_LOGISTICS_HOME_HASH_KEY = "5294y06JbISpM5x9"
ECPAY_LOGISTICS_HOME_HASH_IV = "v77hoKGq4kWxNNIS"

# Logistics (prod placeholders)
ECPAY_LOGISTICS_MERCHANT_ID = ""
ECPAY_LOGISTICS_HASH_KEY = ""
ECPAY_LOGISTICS_HASH_IV = ""

# Payment (stage)
ECPAY_PAYMENT_MERCHANT_ID = "3002607"
ECPAY_PAYMENT_HASH_KEY = "pwFHCqoQZGmho4w6"
ECPAY_PAYMENT_HASH_IV = "EkRm7iFT261dpevs"

# Common fallback keys
ECPAY_HASH_KEY = "XBERn1YOvpM9nfZc"
ECPAY_HASH_IV = "h1ONHk4P4yqbl5LK"

# Default Senders
LOGISTICS_SENDER_NAME = "林粼林"
LOGISTICS_SENDER_PHONE = "0909090909"
LOGISTICS_SENDER_CELLPHONE = ""
LOGISTICS_SENDER_ZIP = "434"
LOGISTICS_SENDER_ADDRESS = "台中市龍井區中山路一段8888號"
LOGISTICS_SENDER_HOME_NAME = ""
LOGISTICS_SENDER_HOME_PHONE = ""
LOGISTICS_SENDER_HOME_CELLPHONE = ""
LOGISTICS_SENDER_HOME_ZIP = ""
LOGISTICS_SENDER_HOME_ADDRESS = ""
LOGISTICS_SENDER_C2C_NAME = ""
LOGISTICS_SENDER_C2C_PHONE = ""
LOGISTICS_SENDER_C2C_CELLPHONE = ""
LOGISTICS_SENDER_C2C_ZIP = ""
LOGISTICS_SENDER_C2C_ADDRESS = ""

# Supabase
SUPABASE_URL = "https://vfpvnxaxngpendzacifd.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcHZueGF4bmdwZW5kemFjaWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNzU4MjgsImV4cCI6MjA3NTY1MTgyOH0.39d7am0EVApKF-MqSDWsyv7P4Na2V8HSLE9JWg5i39Q"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcHZueGF4bmdwZW5kemFjaWZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDA3NTgyOCwiZXhwIjoyMDc1NjUxODI4fQ.I2BMI-e9lWa4j3ztyTeP5QRdqV4Eyh_c16Eq-t2SOTY"

# LINE (backend/front)
BACKEND_LINE_CHANNEL_ID = "2008275679"
BACKEND_LINE_CHANNEL_SECRET = "5e1ed6aaeb82d234168944dc4b870591"
# After switching to custom domains, LINE callback must hit the Worker domain
BACKEND_LINE_REDIRECT_URI = "https://api.marelle.com.tw/backend/auth/line/callback"
FRONTEND_LINE_CHANNEL_ID = "2008146294"
FRONTEND_LINE_CHANNEL_SECRET = "7b1f614b5568a9f3e64d5d3e5737809e"
# Use API Worker origin for LINE OAuth callback; the handler lives on the Worker
FRONTEND_LINE_REDIRECT_BASE = "https://api.marelle.com.tw"

# Session / CORS / Site
ADMIN_SESSION_SECRET = "please-change-me-dev-hmac-secret-32bytes"
ALLOWED_ORIGIN = "https://admin.marelle.com.tw"
FRONTEND_SITE_URL = "https://marelle.com.tw"


