// 台灣行政區資料（精選直轄市/市，含常用郵遞區號，3 碼制）
// 可依需要擴充至所有縣市與鄉鎮市區。

export const TAIWAN_CITY_DISTRICTS = {
  '臺北市': [
    { name: '中正區', zip: '100' },
    { name: '大同區', zip: '103' },
    { name: '中山區', zip: '104' },
    { name: '松山區', zip: '105' },
    { name: '大安區', zip: '106' },
    { name: '萬華區', zip: '108' },
    { name: '信義區', zip: '110' },
    { name: '士林區', zip: '111' },
    { name: '北投區', zip: '112' },
    { name: '內湖區', zip: '114' },
    { name: '南港區', zip: '115' },
    { name: '文山區', zip: '116' },
  ],
  '新北市': [
    { name: '板橋區', zip: '220' },
    { name: '新莊區', zip: '242' },
    { name: '中和區', zip: '235' },
    { name: '永和區', zip: '234' },
    { name: '土城區', zip: '236' },
    { name: '樹林區', zip: '238' },
    { name: '三峽區', zip: '237' },
    { name: '鶯歌區', zip: '239' },
    { name: '三重區', zip: '241' },
    { name: '蘆洲區', zip: '247' },
    { name: '五股區', zip: '248' },
    { name: '泰山區', zip: '243' },
    { name: '林口區', zip: '244' },
    { name: '淡水區', zip: '251' },
    { name: '八里區', zip: '249' },
    { name: '三芝區', zip: '252' },
    { name: '石門區', zip: '253' },
    { name: '金山區', zip: '208' },
    { name: '萬里區', zip: '207' },
    { name: '汐止區', zip: '221' },
    { name: '瑞芳區', zip: '224' },
    { name: '貢寮區', zip: '228' },
    { name: '平溪區', zip: '226' },
    { name: '雙溪區', zip: '227' },
    { name: '石碇區', zip: '223' },
    { name: '深坑區', zip: '222' },
    { name: '新店區', zip: '231' },
    { name: '坪林區', zip: '232' },
    { name: '烏來區', zip: '233' },
  ],
  '桃園市': [
    { name: '桃園區', zip: '330' },
    { name: '中壢區', zip: '320' },
    { name: '平鎮區', zip: '324' },
    { name: '八德區', zip: '334' },
    { name: '楊梅區', zip: '326' },
    { name: '蘆竹區', zip: '338' },
    { name: '大溪區', zip: '335' },
    { name: '龍潭區', zip: '325' },
    { name: '龜山區', zip: '333' },
    { name: '大園區', zip: '337' },
    { name: '觀音區', zip: '328' },
    { name: '新屋區', zip: '327' },
    { name: '復興區', zip: '336' },
  ],
  '臺中市': [
    { name: '中區', zip: '400' },
    { name: '東區', zip: '401' },
    { name: '南區', zip: '402' },
    { name: '西區', zip: '403' },
    { name: '北區', zip: '404' },
    { name: '北屯區', zip: '406' },
    { name: '西屯區', zip: '407' },
    { name: '南屯區', zip: '408' },
    { name: '太平區', zip: '411' },
    { name: '大里區', zip: '412' },
    { name: '霧峰區', zip: '413' },
    { name: '豐原區', zip: '420' },
    { name: '后里區', zip: '421' },
    { name: '石岡區', zip: '422' },
    { name: '東勢區', zip: '423' },
    { name: '新社區', zip: '424' },
    { name: '潭子區', zip: '427' },
    { name: '大雅區', zip: '428' },
    { name: '神岡區', zip: '429' },
    { name: '大肚區', zip: '432' },
    { name: '沙鹿區', zip: '433' },
    { name: '龍井區', zip: '434' },
    { name: '梧棲區', zip: '435' },
    { name: '清水區', zip: '436' },
    { name: '大甲區', zip: '437' },
    { name: '外埔區', zip: '438' },
    { name: '大安區', zip: '439' },
    { name: '和平區', zip: '424' },
  ],
  '臺南市': [
    { name: '中西區', zip: '700' },
    { name: '東區', zip: '701' },
    { name: '南區', zip: '702' },
    { name: '北區', zip: '704' },
    { name: '安平區', zip: '708' },
    { name: '安南區', zip: '709' },
    { name: '永康區', zip: '710' },
    { name: '歸仁區', zip: '711' },
    { name: '新化區', zip: '712' },
    { name: '仁德區', zip: '717' },
    { name: '關廟區', zip: '718' },
    { name: '新市區', zip: '744' },
    // 其餘行政區可再補充
  ],
  '高雄市': [
    { name: '新興區', zip: '800' },
    { name: '前金區', zip: '801' },
    { name: '苓雅區', zip: '802' },
    { name: '鹽埕區', zip: '803' },
    { name: '鼓山區', zip: '804' },
    { name: '旗津區', zip: '805' },
    { name: '前鎮區', zip: '806' },
    { name: '三民區', zip: '807' },
    { name: '楠梓區', zip: '811' },
    { name: '小港區', zip: '812' },
    { name: '左營區', zip: '813' },
    { name: '鳳山區', zip: '830' },
    { name: '大寮區', zip: '831' },
    { name: '仁武區', zip: '814' },
    { name: '岡山區', zip: '820' },
    { name: '路竹區', zip: '821' },
    { name: '橋頭區', zip: '825' },
    { name: '梓官區', zip: '826' },
    { name: '彌陀區', zip: '827' },
    { name: '永安區', zip: '828' },
    { name: '湖內區', zip: '829' },
    { name: '大樹區', zip: '840' },
    { name: '大社區', zip: '815' },
    // 其餘行政區可再補充
  ],
  '基隆市': [
    { name: '仁愛區', zip: '200' },
    { name: '信義區', zip: '201' },
    { name: '中正區', zip: '202' },
    { name: '中山區', zip: '203' },
    { name: '安樂區', zip: '204' },
    { name: '暖暖區', zip: '205' },
    { name: '七堵區', zip: '206' },
  ],
  '新竹市': [
    { name: '東區', zip: '300' },
    { name: '北區', zip: '300' },
    { name: '香山區', zip: '300' },
  ],
  '嘉義市': [
    { name: '東區', zip: '600' },
    { name: '西區', zip: '600' },
  ],
};

export const TAIWAN_CITIES = Object.keys(TAIWAN_CITY_DISTRICTS);

export function getDistrictsByCity(city) {
  return TAIWAN_CITY_DISTRICTS[city] || [];
}
